name: claude-was-here Preserve git Notes (Post-merge)

on:
  pull_request:
    types: [closed]

jobs:
  attach-claude-notes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}  # Checkout the target branch
          
      - name: Download Claude notes artifact
        uses: actions/download-artifact@v4
        with:
          name: claude-notes-pr-${{ github.event.number }}
          path: ./artifacts/
        continue-on-error: true
        
      - name: Check if Claude notes exist
        id: check-notes
        run: |
          if [ -f "./artifacts/claude_commits_data.txt" ]; then
            echo "notes_exist=true" >> $GITHUB_OUTPUT
            echo "Found Claude notes artifact"
          else
            echo "notes_exist=false" >> $GITHUB_OUTPUT
            echo "No Claude notes artifact found"
          fi
          
      - name: Process and attach Claude notes to merge commit
        if: steps.check-notes.outputs.notes_exist == 'true'
        run: |
          # Get the latest commit (should be the merge/squash commit)
          latest_commit=$(git rev-parse HEAD)
          echo "Latest commit: $latest_commit"
          
          # Get the base commit to compare against
          base_commit=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})
          echo "Base commit: $base_commit"
          
          # Run the Claude lines analysis using the installed script
          python3 .github/scripts/analyze-claude-lines.py ./artifacts/claude_commits_data.txt "$base_commit" "$latest_commit" > final_claude_note.txt
          
          # Add the consolidated note to the merge commit
          git notes add -F final_claude_note.txt "$latest_commit"
          
          # Push the notes
          git push origin refs/notes/commits
          
          echo "Successfully attached consolidated Claude notes to commit $latest_commit"
          echo "Final note content:"
          cat final_claude_note.txt